### ISSUE TITLE
Why a viewbox of viewbox="0,0,194,186"

### ISSUE THREAD

**Issue by gautamz07** [pguso/js-plugin-circliful#103]
@pguso just a curious question really , why is it that your've used such unusual number for the viewbox , initially when i was trying to customize a small portion of the code, that kind of got me stumped for a minute , any reason for using only these specific values ? why not just  viewbox="0,0,200,200" ? make the calculations much more straightforward. 

Thank you. 

https://github.com/pguso/jquery-plugin-circliful/blob/master/js/jquery.circliful.js#L140

**Comment by pguso** [comment]
sorry for my late answer. i reimplemented the library from scratch, if your issue still isnt solved, please open it again.
