### ISSUE TITLE
iOS bug - circle rotation

### ISSUE THREAD

**Issue by aksun1** [pguso/js-plugin-circliful#109]
On iOS, the circliful is wrongly rotated, the colorized circle starts at the left; check the picture:

![IPAD Screenshot](https://s14.postimg.org/tr460g0bz/IMG_0053.png)

This happens at least on iPhone 5(Safari, Chrome) and iPad Air 2 with iOS 10.  On windows 10 it's working properly. Any fix?

**Comment by aksun1** [comment]
Do you copy @pguso?

**Comment by pguso** [comment]
Sorry but right now i dont have much free time beside my work...i will fix it as soon as i can but it can take some time till i can do so.

**Comment by aksun1** [comment]
Yeah just want to let you know of this major issue.

**Comment by terenzeyuen** [comment]
Any resolution?

**Comment by terenzeyuen** [comment]
Fixed it (temporarily). Just add 0.1 degrees to the rotation.

**Comment by DC-development** [comment]
Hi @aksun1, does the solution from @terenzeyuen work for you?

**Comment by pguso** [comment]
sorry for my late answer. i reimplemented the library from scratch, if your issue still isnt solved, please open it again.
