### ISSUE TITLE
How to make it fill my container

### ISSUE THREAD

**Issue by RoyWu666** [pguso/js-plugin-circliful#118]

**Comment by hunterae** [comment]
@RoyWu666 , found a hacky way around this:

> var progressCircle = $('.progress-circle');
  progressCircle.circliful();
  progressCircle.find("circle").attr("r", 70);
  progressCircle.find(".border").attr("stroke-dasharray", 0);

**Comment by RoyWu666** [comment]
@hunterae Thank you very much,you are very good~

**Comment by RoyWu666** [comment]
@hunterae , Thank you very much,you are so awesome!

**Comment by hunterae** [comment]
No problem @RoyWu666. Happy to help, as I had the same issue. I'll see about putting in a PR to have that as an option.

**Comment by RoRElessar** [comment]
Is there any way to make a progress bar stay the same, after resizing the radius? For example, before changing the radius, the progress bar is 5 (changed 100% to 5), and after resizing, the value is still 5, but the progress bar is nearly 66%

**Comment by hunterae** [comment]
@RoRElessar:
It appears that this script is assuming that the radius is 57 when calculating the percentage of the circle to mark as "finished". It took me a bit to realize that a radius of 57 calculates to a circumference of roughly 360 (i.e. 2 * Pi * 57 ~= 360). I'm not sure there is a way to apply a hack to the way the progress calculation is applied. 

If the radius were changed to 70 as I showed above, the circumference would be roughly 439.6. Thus to show 5%, the script would somehow need to be updated to set the stroke-dasharray of the circle element with class "circle" to "21.98, 20000" (i.e. .05*439.6 = 21.98). You may need to download and hack the actual script to fix the way it does its calculations.

**Comment by pguso** [comment]
sorry for my late answer. i reimplemented the library from scratch, if your issue still isnt solved, please open it again.
