### ISSUE TITLE
Utlizing the whole container without any margin/padding

### ISSUE THREAD

**Issue by githubmitra** [pguso/js-plugin-circliful#136]
There is difference is size between the svg-container and the circle inside it. When I reduce the size of the outer container the size of the circle inside also decreases. My webpage has limited space and I need to fully utilize the space for the circle without any gaps(margin). Is there a way to remove all the white space.

**Comment by pguso** [comment]
sorry for my late answer. i reimplemented the library from scratch, if your issue still isnt solved, please open it again.
