### ISSUE TITLE
in mobile not working

### ISSUE THREAD

**Issue by SoyDiego** [pguso/js-plugin-circliful#154]
Hi, your plugin is amazing, thanks!!
But I have an issue. In my mobile (chrome), my circles don't start but in my browsers (laptop) works perfectly.
Can you help me?

Thanks and sorry for my english! :)

**Comment by pguso** [comment]
@SoyDiego do you still need a fix for that or did you solved it already?

**Comment by pguso** [comment]
sorry for my late answer. i reimplemented the library from scratch, if your issue still isnt solved, please open it again.
