### ISSUE TITLE
How can I use data-attributes with percentages[index].percent?

### ISSUE THREAD

**Issue by dynelee** [pguso/js-plugin-circliful#162]
Hello . First, I appreciate your plug-in I really enjoy with this plug-in so much.
I have some question to use it.
I'd like to make it works with my DB.
So I usually set data-attributes with rows that i selected from DB with sql.
<div id="test-circle" data-animation="1" data-animationStep="5" data-percent="<%=rows[i].percentage%>"></div>

but, I don't know how to make this with 'multiPercentage'
I want to set data-percentages and also percentages[index].percent  as data what i found from DB.

How can I use data-attributes to percentages[index].percent?? #

**Comment by pguso** [comment]
sorry for my late answer. i reimplemented the library from scratch, if your issue still isnt solved, please open it again.
