### ISSUE TITLE
Can you draw a circular progress bar like this? What I want is a circle of about 80%.

### ISSUE THREAD

**Issue by srdc2014** [pguso/js-plugin-circliful#163]
![image](https://user-images.githubusercontent.com/6275084/53682424-74dee500-3d30-11e9-9df3-c4faed29e0af.png)

Can you draw a circular progress bar like this? What I want is a circle of about 80%.

**Comment by pguso** [comment]
implemented, please see the configuration here https://stackblitz.com/edit/js-2m2bs7
