### ISSUE TITLE
Half circle is not showing properly for 100%

### ISSUE THREAD

**Issue by mhetreramesh** [pguso/js-plugin-circliful#165]
Problem: For half cricle, the chart is going beyond limit for 100%. See example below:

My code is like:
```
    $( document ).ready(function() {
        $("#test-circle5").circliful({
          animationStep: 4,
          foregroundBorderWidth: 10,
          backgroundBorderWidth: 15,
          percent: 100,
          halfCircle: 1,
        });
    });
```

Here is the jsfiddle link:
[https://jsfiddle.net/x7kab15v/2/](https://jsfiddle.net/x7kab15v/2/)

**Screenshot**:
![image](https://user-images.githubusercontent.com/3095445/54424047-586c8080-4712-11e9-92a2-6256ff0d85fe.png)

**Comment by pguso** [comment]
sorry for my late answer. i reimplemented the library from scratch, if your issue still isnt solved, please open it again.
