### ISSUE TITLE
Circle With Number greater than 100

### ISSUE THREAD

**Issue by grayniall** [pguso/js-plugin-circliful#167]
Hi,

Was just trying out the new version and noticed that if you had a number greater than 100 the visualization was a bit off

Before
animationStep
![image](https://user-images.githubusercontent.com/517042/80608306-79835400-8a2e-11ea-9ba5-0f675e873120.png)

Now:
![image](https://user-images.githubusercontent.com/517042/80608361-90c24180-8a2e-11ea-8019-945c9b2ab374.png)

Wasn't sure if it was a feature before that was taken out or a bug now :)

Thanks

**Comment by pguso** [comment]
Yes, sorry this is a bug. I will fix it tomorrow :)

**Comment by pguso** [comment]
Fixed this issue. If there's anything else i can do, don't hesitate to ask.
