### ISSUE TITLE
API Update circle values additionalCssClasses

### ISSUE THREAD

**Issue by carlosFX0227** [pguso/js-plugin-circliful#169]
Hello, how to use additionalCssClasses with the values update api

circle.update([
{type: 'percent', value: 70},
{type: 'additionalCssClasses', value:},
]);

Could you guide me
Thanks, great plugin

**Comment by pguso** [comment]
Yes of course, additionalCssClasses takes an object as an input, i made an jsfiddle and set all possible properties of  additionalCssClasses, all properties of additionalCssClasses are optional so you can just the ones you need https://jsfiddle.net/9kn74swv/

**Comment by carlosFX0227** [comment]
Thanks
