### ISSUE TITLE
Is there any way to update on AJAX success response?

### ISSUE THREAD

**Issue by vpadhariya** [pguso/js-plugin-circliful#50]
Hi,

I had used this great chart in few of my projects for dashboard chart purpose, however in one of my projects I want this to be re-draw based on AJAX response is this possible?

your help is much appreciated.

**Comment by ztoliver** [comment]
Although not elegant, I have done this by removing the element, creating a new one and initializing the element with circliful after.

```
                        $("#myCpuStat").remove();
                        $("#cpu-chart").append("<div class=\"col s6\" id=\"myCpuStat\" data-dimension=\"250\" data-text=\"" + cpuRounded + "%\" data-info=\"CPU\" data-width=\"30\" data-fontsize=\"38\" data-percent=\"" + data + "\" data-fgcolor=\"#4caf50\" data-bgcolor=\"#eee\" data-fill=\"#ddd\" data-total=\"100\" data-icon=\"long-arrow-up\" data-icon-size=\"28\" data-icon-color=\"#fff\"></div>");
                        $("#myCpuStat").circliful();
```

**Comment by pguso** [comment]
With the new implementation you can call the update function
