### ISSUE TITLE
Update percentage and circle

### ISSUE THREAD

**Issue by fernandomatal** [pguso/js-plugin-circliful#6]
Is there a way to update the percentage and the circle without re doing the circle?

I just want to update the circle every time the user performs certain action.

Thank you.

**Comment by PanRu** [comment]
Thanks so much, it helps a lot. :+1:

**Comment by jpbrousseau** [comment]
Works for me! Thanks a lot!

**Comment by paddotk** [comment]
For anyone interested, I found a way to make the percentage text work as an updating counter. This will add up the displayed number along with the animating bar.

var updatePerc = 0;
									function update() {
										setInterval(function(){
											if(updatePerc <= 57){//this one goes until 57%
												updatePerc++;
												$('#circFull').empty().removeData().attr('data-percent', updatePerc).attr('data-text', updatePerc+'%').attr('data-animationstep', '50').circliful();//use a high number for animationstep so you don't see the animation going over and over again.
											}
										}, 50);//miliseconds for the interval. Make this number higher for slower animation.
									}

The method I used with a high number in animationstep is maybe not the ideal way, but it works fairly well. The colored bar may flicker a bit though. Don't use too high a number to avoid using more processing power than neccesary.

P.s. if anyone knows of a better way, I'd like to know!! :D

**Comment by kylescousin** [comment]
@paddotk You can just do

$('#your-circle').find('.circle-text').html(updatePerc + '%');

No css positioning needed

**Comment by paddotk** [comment]
@kylescousin This does exactly the same... Assuming the '`.circle-text`' still refers to the `span` inside the circle div?

**Comment by Skinass** [comment]
# Here is my solution
```javascript
function draw(idwhere,idwhat,options){   
    $("#"+idwhat).remove();
    $("#"+idwhere).append('<div id="'+idwhat+'"></div>');
    $.each(options, function(i, val){
        $("#"+idwhat).attr('data-'+i, val)
    });
    $("#"+idwhat).circliful();
}
```

And if you dont want to redraw circles there is an extended circliful lib
https://github.com/mikael-desharnais/circliful-reloaded/tree/master/js
But it has some bugs in drawing more than 2 circles

**Comment by dougwells** [comment]
sQu1rr ... worked great.  Wasted several hours trying to do this myself until I found your solution.  THANK YOU!

**Comment by gesaleh** [comment]
Hi
I'm trying to make a half circle update using the sQu1rr method but it just erase and redraw a full circle with always 75% value.

is there a simple way to make the circle update ?

**Comment by DarushDev** [comment]
To change the foreground circle degree I used the following method:

**`$("#circle").children("svg").eq(0).children("circle").eq(1).css("stroke-dasharray", degree + ", 20000");`**

where **degree** is the between 0 and 360. So you only update the outer circle degree without recreating the circle object.

**Comment by jauntum** [comment]
@gesaleh  Same here, my solution is a combination of answers above:

```
var container = $('#id]').parent();
$('#[id]').remove();
container.append('<div id="id]" class="animate"></div>');
$("#id]").attr("data-percent", [new percentage]);
$("#id]").circliful();
```

**Comment by pguso** [comment]
with the new implementation you can call the update function to set the percentage

circle.update({type: 'percent', value: 50});
